In [4]:
import numpy
n=numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [2]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [3]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
# pip install opencv-python
# pip install ipykernel
# python -m ipykernel install --user --name=venv_dml

import cv2
im_g = cv2.imread("smallgray.png",0)  # gray BGR values from 0 to 255  (not RGB)
print(im_g) 

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [3]:
im_g = cv2.imread("smallgray.png",1) # 3D array with R, G and B layers, transposed
im_g 

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [4]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [5]:
im_g = cv2.imread("smallgray.png",0)
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [8]:
for i in im_g:
    print(i)
for i in im_g.T:
    print(i)
for i in im_g.flat:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [15]:
imh = numpy.hstack((im_g,im_g))
print(imh)
imv = numpy.vstack((im_g, im_g))
print(imv)
lsth = numpy.hsplit(imh, 2)  # slice in 3 pieces, horizontally
print(lsth)
lstv = numpy.vsplit(imv, 3)
print(lstv)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
