In [21]:
import pandas as pd
import quandl
import numpy as np
import math
from sklearn import preprocessing, cross_validation, svm
from sklearn.linear_model import LinearRegression   

df = quandl.get('WIKI/GOOGL')  # get historic of a stock

df = df[["Adj. Open","Adj. High","Adj. Low","Adj. Close","Adj. Volume"]]

df["HL_PCT"] = ((df["Adj. High"] - df["Adj. Close"]) / df["Adj. Close"]) * 100     # High / Close Percentage
df["PCT_change"] = ((df["Adj. Close"] - df["Adj. Open"]) / df["Adj. Open"]) * 100  # Close/Open Precentage

df=df[["Adj. Close","HL_PCT","PCT_change","Adj. Volume"]]

forecast_col = "Adj. Close";
df.fillna(-99999, inplace = True)

forecast_out = int(math.ceil(0.01*len(df)))
# print ("forecast_out =" + str(forecast_out))

df["label"] = df[forecast_col].shift(-forecast_out)

df

Adj. Close    HL_PCT  PCT_change  Adj. Volume      label
Date                                                                 
2004-08-19    50.322842  3.712563    0.324968   44659000.0  69.639972
2004-08-20    54.322689  0.710922    7.227007   22834300.0  69.078238
2004-08-23    54.869377  3.729433   -1.227880   18256100.0  67.839414
2004-08-24    52.597363  6.417469   -5.726357   15247300.0  68.912727
2004-08-25    53.164113  1.886792    1.183658    9188600.0  70.668146
2004-08-26    54.122070  0.037068    2.820391    7094800.0  71.219849
2004-08-27    53.239345  2.326896   -1.803885    6211700.0  72.278116
2004-08-30    51.162935  3.411430   -3.106003    5196700.0  74.810934
2004-08-31    51.343492  1.308977    0.048866    4917800.0  74.199045
2004-09-01    50.280210  2.713217   -2.385589    9138200.0  70.462511
2004-09-02    50.912161  0.847207    2.442224   15118600.0  74.921275
2004-09-03    50.159839  1.729827   -0.931154    5152400.0  86.481962
2004-09-07    50.947269  0.413467    0.564301    5847500.0  93.990139
2004-09-08    51.308384  0.713587    1.548541    4985600.0  91.181468
2004-09-09    51.313400  0.390969   -0.185366    4061700.0  93.272925
2004-09-10    52.828075  1.167758    3.804080    8698800.0  96.949273
2004-09-13    53.916435  0.846512    0.815905    7844100.0  95.615155
2004-09-14    55.917612  0.457440    3.769546   10828900.0  98.318500
2004-09-15    56.173402  1.991071    1.302460   10713000.0  97.736704
2004-09-16    57.161452  1.605686    1.450952    9266300.0  96.131750
2004-09-17    58.926902  0.000000    2.683097    9472500.0  92.635958
2004-09-20    59.864797  1.876676    2.060710   10628700.0  84.937193
2004-09-21    59.102444  2.189409   -1.963394    7228700.0  86.542147
2004-09-22    59.373280  1.089711    0.791826    7581200.0  84.611187
2004-09-23    60.597057  1.498096    1.666106    8535600.0  84.189886
2004-09-24    60.100525  3.563381   -0.942382    9123400.0  91.793357
2004-09-27    59.313094  2.215457   -1.087320    7066100.0  91.281778
2004-09-28    63.626409  0.425666    4.713165   16929000.0  92.721222
2004-09-29    65.742942  3.005798    3.595985   30516400.0  86.539640
2004-09-30    65.000651  2.083333   -0.230179   13758000.0  86.517070
...                 ...       ...         ...          ...        ...
2017-10-25   991.460000  0.299558    0.526225    1368042.0        NaN
2017-10-26   991.420000  1.522059   -0.706080    1827682.0        NaN
2017-10-27  1033.670000  2.897443    0.259944    5139945.0        NaN
2017-10-30  1033.130000  0.648515    0.385751    2245352.0        NaN
2017-10-31  1033.040000  0.770541    0.003872    1490660.0        NaN
2017-11-01  1042.600000  0.504508    0.605990    2105729.0        NaN
2017-11-02  1042.970000  0.244494    0.286541    1233333.0        NaN
2017-11-03  1049.990000  0.063810    0.694318    1370874.0        NaN
2017-11-06  1042.680000  0.950435   -0.611953     897897.0        NaN
2017-11-07  1052.390000  0.096922    0.261039    1254965.0        NaN
2017-11-09  1047.720000  0.301607   -0.026718    1776722.0        NaN
2017-11-10  1044.150000  0.237514    0.026823     955500.0        NaN
2017-11-13  1041.200000  0.724164    0.038432     914852.0        NaN
2017-11-14  1041.640000  0.063362    0.377751     982782.0        NaN
2017-11-15  1036.410000  0.310688    0.136232     900695.0        NaN
2017-11-16  1048.470000  0.313791    0.935740    1125995.0        NaN
2017-11-17  1035.890000  1.458649   -1.325014    1286044.0        NaN
2017-11-20  1034.660000  0.390466   -0.129344     850423.0        NaN
2017-11-21  1050.300000  0.008569    0.986501    1075568.0        NaN
2017-11-22  1051.920000  0.333676    0.072301     721498.0        NaN
2017-11-24  1056.520000  0.336009    0.202013     825342.0        NaN
2017-11-27  1072.010000  0.096081    1.269637    1708195.0        NaN
2017-11-28  1063.290000  1.571537   -0.996285    1694098.0        NaN
2017-11-29  1037.380000  2.061925   -1.780000    2737664.0        NaN
2017-11-30  1036.170000

In [14]:
# VERSION 1   
df1 = df
df1.dropna(inplace=True)
x = np.array(df1.drop(['label'], 1))  # columns without label 
y = np.array(df1['label'])            # array from column label

x = preprocessing.scale(x)

x_train, x_test, y_train, y_test = cross_validation.train_test_split(x, y, test_size=0.2) # shuffle and use 20% data as test data 

clf = LinearRegression()
clf.fit(x_train, y_train)
accuracy =  clf.score(x_test, y_test)

accuracy

0.97546690888512577

In [28]:
# VERSION 1   
df2 = df

x = np.array(df2.drop(['label'], 1))  # columns without label 
y = np.array(df2['label'])            # array from column label

x = preprocessing.scale(x)

print(x)
x_lately = x[-forecast_out:]
print (x_lately)
x = x[:-forecast_out:]
x_lately = x[-forecast_out:]
print (x_lately)

[[-1.43832368  2.33958436  0.23152573  4.42841791]
 [-1.42157182 -0.31244291  4.82309448  1.79570797]
 [-1.41928222  2.35448975 -0.80150318  1.24344047]
 ..., 
 [ 2.62113075  0.539492    0.58189391 -0.72623941]
 [ 2.67607896 -0.35366567  1.07552932 -0.7936143 ]
 [ 2.72570824 -0.57262632  0.5611165  -0.78539073]]
[[  2.54674964e+00  -4.57278270e-01  -1.77330287e-01  -7.56491075e-01]
 [  2.56027729e+00  -6.25854519e-01  -1.15455287e-01  -7.69587495e-01]
 [  2.47848319e+00   8.74829313e-01  -1.28447250e+00  -7.62937654e-01]
 [  2.49083816e+00  -8.71737581e-01   1.49537732e-01  -7.87943857e-01]
 [  2.50327690e+00  -6.75893777e-01   3.65411939e-01  -7.93763161e-01]
 [  2.50310937e+00   4.04217589e-01  -4.54376858e-01  -7.38316864e-01]
 [  2.68005768e+00   1.61940486e+00   1.88269182e-01  -3.38759129e-01]
 [  2.67779609e+00  -3.67581679e-01   2.71962156e-01  -6.87933401e-01]
 [  2.67741916e+00  -2.59768008e-01   1.79177006e-02  -7.78971772e-01]
 [  2.71745764e+00  -4.94815374e-01   4.1847569

In [ ]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(x, y, test_size=0.2) # shuffle and use 20% data as test data 

clf = LinearRegression()
clf.fit(x_train, y_train)
accuracy =  clf.score(x_test, y_test)